### PR TITLE
[bugfix] Add proper handling to FluixMixerBlockEntity.java

### PR DESCRIPTION
**Pull request by lineargraph**
Fluids now merge into existing stacks.
Fluids are no matched against partial recipes if no fluid is present in the machine.

### CODE REVIEW

**Comment by vini2003** [comment]
Won't this have to be added to all other machines as well?

**Comment by vini2003** [comment]
If so I'll get around to that soon:tm:.

**Comment by lineargraph** [comment]
I'm not sure about other machines; I haven't checked most of them. In particular this handler contains a lot of logic for the double inputs, which shouldn't be necessary for other (non dual input) machines.

**Comment by vini2003** [comment]
I'll check tomorrow, your fix does look solid. Gonna see if I need to apply it elsewhere. For now, good work!

**Pull request merged**
