### PR TITLE
Updated FluidMixingRecipe to check for inputslot for both fluids.

### PR DESCRIPTION
**Pull request by johannesmateboer**

### CODE REVIEW

**Comment by Doorriiaann** [comment]
🚀🚀🚀🚀🚀🚀🚀🚀🚀Thanks m8, works great🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

**Comment by vini2003** [comment]
If ya'll say it's good, then it's good. Thanks!

**Comment by vini2003** [comment]
...well, that should've been PR'd to development-1.16.5.

**Comment by vini2003** [comment]
Count it as merged and I'll just commit it on my end.

**Pull request merged**
