### PR TITLE
Make liquid hydrogen explode when touching liquid oxygen

### PR DESCRIPTION
**Pull request by Pyrofab**
I noticed Astromine has a distinct lack of boom. So I added some boom.

`hydrogen + oxygen = water + boom`

### CODE REVIEW

**Comment by vini2003** [comment]
Out of all PRs, I believe this to be the most important by far.

**Comment by Neubulae** [comment]
ngl this is legit cool 10/10

**Comment by Shnupbups** [comment]
My only fault with this is I dislike the idea of assigning functionality like this to `c` tags. `c` tags to me are meant to sort of be reserved only for recipe use and similar things? I dunno.

So maybe add an astromine-specific hydrogen and oxygen tag (that is then nested into the `c` tag) and use that instead?

**Comment by vini2003** [comment]
I disagree. `c:hydrogen`s should always work the same way, so this is perfectly fit.

**Comment by Shnupbups** [comment]
I just worry that perhaps some other mod will add hydrogen or oxygen and not want this behaviour for some reason, e.g. perhaps they have their own behaviour for when they touch.

**Comment by Neubulae** [comment]
Make it so it only works when either of the fluid contains `astromine` tag.

**Comment by shedaniel** [comment]
just make `astromine:hydrogen` tag as well

**Comment by vini2003** [comment]
I don't see why anyone would want not to have explosions.

**Comment by vini2003** [comment]
@Pyrofab if you feel like having some fun, it would also be very cool to have oil explode in flames.

**Comment by Pyrofab** [comment]
Here you go, gases will only explode if they are in the astromine tags.
@vini2003 I don't think oil explosions are in scope for this PR, could certainly be added later.

**Comment by vini2003** [comment]
Suppose this is good to go.

**Pull request merged**
