### PR TITLE
Added fluid pump block and entity

### PR DESCRIPTION
**Pull request by javiersuweijie**
Fluid pump with an extending pipe.

After running for sometime and draining out a crude oil well.

- [x] Added new pump block with draining logic
- [x] Added a build-craft like extending pipe
- [ ] Configurable + default settings (pump speed, max searched blocks)
- [x] Model for extending pipe (Fence currently used as a placeholder model)
- [ ] Crafting recipe
- [ ] Manual information page

### CODE REVIEW

**Comment by javiersuweijie** [comment]
Updated with a new block for pump pipe

**Comment by Ueaj-Kerman** [comment]
I approve

**Comment by vini2003** [comment]
Hey, that's cool.

**Comment by vini2003** [comment]
Requires adaptation for merge with development-1.16.5; gonna have to see how to go about that.

**Comment by Domaman202** [comment]
Hi!

**Comment by Domaman202** [comment]
Go to work with my mod?)))

**Comment by vini2003** [comment]
Hey, sorry for never getting around to this - I got busy with work and didn't have enough time to check it out. We've added a Pump in the mod now, so I'll be closing it, thank you for the idea & example! It just couldn't be merged directly since we had to rewrite half of the mod.

**Pull request closed without merging**
